version: "3"

services:
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/app/db/
  restapi:
    build: .
    container_name: app
    command: gunicorn --bind 0.0.0.0:5000 main:app
    ports:
      - 5000:5000